"""Tier 0: discover every source file, measure it, map its imports, and shard it for the scouts."""

import datetime
import fnmatch
import subprocess
from dataclasses import asdict, dataclass
from pathlib import Path

import clones as clonelib
import graph as graphlib
import reach as reachlib
from gitlog import WINDOW_DAYS, change_history
from imports import ImportResolver
from lenses import lenses_for
from languages import language_for
from metrics import classify_lines, measure
from packing import pack
from structure import analyze, identifier_index
from workspace import SKILL_DIR, read_json, task_header, task_id_for, write_json

IGNORED_DIRS = {
    ".git", ".hg", ".svn", "node_modules", "bower_components", "vendor", "third_party",
    "dist", "build", "out", "target", "obj", ".next", ".nuxt", ".svelte-kit", ".output",
    "coverage", "htmlcov", "__pycache__", ".venv", "venv", "env", ".tox", ".nox", ".mypy_cache",
    ".pytest_cache", ".ruff_cache", ".gradle", ".idea", ".vscode", "Pods", ".terraform",
    ".slop_scan", "site-packages", "migrations", "third-party", "thirdparty", "3rdparty",
}
IGNORED_GLOBS = ("*.min.js", "*.min.css", "*.bundle.js", "*.pb.go", "*_pb2.py", "*.g.dart", "*.generated.*", "*.d.ts")
GENERATED_MARKERS = ("@generated", "do not edit", "auto-generated", "autogenerated", "code generated by")
GENERATED_HEADER_LINES = 40  # generators stamp the top of the file, sometimes below a license
_COMMENT_STARTS = ("#", "//", "/*", "*", "<!--", "--", ";", '"""', "'''")
TEST_DIR_NAMES = {"test", "tests", "spec", "specs", "__tests__", "testing", "e2e"}
MAX_FILE_BYTES = 1_000_000


@dataclass
class InventorySettings:
    shard_loc: int  # max lines of code per scout task
    shard_files: int  # max files (or file segments) per scout task
    chunk_lines: int  # files longer than this are split into segments reviewed separately
    lenses: list  # tier-1 lens names; every shard gets one task per lens
    include_tests: bool
    exclude: list
    extra_extensions: dict
    history_days: int = WINDOW_DAYS  # churn window, ending at the newest commit


def run_inventory(workspace, root, settings):
    root = Path(root).resolve()
    tier1_lenses = lenses_for("tier1", settings.lenses)
    skipped = {"generated": 0, "too_large": 0, "unreadable": 0, "not_code": 0, "excluded": 0}
    sources, paths = {}, []
    generated = {}  # not reviewed, but reachability follows their imports (route trees, codegen barrels)
    for relpath in _candidate_paths(root):
        if any(fnmatch.fnmatch(relpath, pattern) for pattern in settings.exclude):
            skipped["excluded"] += 1
            continue
        paths.append(relpath)
        language = language_for(Path(relpath), settings.extra_extensions)
        if language is None:
            continue
        is_test = _is_test(relpath)
        if is_test and not settings.include_tests:
            skipped["excluded"] += 1
            continue
        text, reason = _read_source(root / relpath)
        if reason:
            skipped[reason] += 1
            if reason == "generated":
                generated[relpath] = (language, text)
            continue
        sources[relpath] = (language, text, is_test)

    if not sources:
        raise SystemExit(f"No source files found under {root}")

    resolver = ImportResolver(sources, lambda rel: _read_optional(root / rel))
    file_edges, files, units = {}, [], []
    for relpath, (language, text, is_test) in sorted(sources.items()):
        targets, unresolved = resolver.resolve(relpath, language.name, text)
        file_edges[relpath] = targets
        files.append({
            "path": relpath,
            "language": language.name,
            "module": graphlib.module_of(relpath),
            "is_test": is_test,
            "external_imports": unresolved,
            **measure(text, language),
        })
        units.extend(_review_units(files[-1], text, settings.chunk_lines))

    graph = graphlib.build_graph(file_edges)
    companions = graphlib.companion_headers(file_edges)
    history, file_history, commits = change_history(root, [entry["path"] for entry in files], settings.history_days)
    index = identifier_index({path: text for path, (_, text, _) in sources.items()})
    duplication = clonelib.detect(
        {path: (language, text) for path, (language, text, _) in sources.items()},
        lambda text, language: classify_lines(text.splitlines(), language),
    )
    reach, reach_summary = reachlib.analyze(paths, sources, files, file_edges, resolver,
                                            lambda rel: _read_optional(root / rel), generated)
    importers = {}
    for entry in files:
        path = entry["path"]
        language, text, _ = sources[path]
        importers[path] = graphlib.importers_of(path, graph, companions)
        entry["fan_out"] = len(graph["imports"][path])
        entry["fan_in"] = len(importers[path])
        if path in companions:
            entry["interface"] = companions[path]
        entry.update(file_history[path])
        entry.update(duplication["per_file"][path])
        entry.update(reach[path])
        entry["structure"] = analyze(path, text, language, index, importers[path])

    clone_report = {
        "pairs": duplication["pairs"],
        "total_pairs": duplication["total_pairs"],
        "module_pairs": clonelib.module_pairs(duplication["pairs"], graphlib.module_of),
        "parallel_trees": clonelib.parallel_trees(
            [entry["path"] for entry in files], {entry["path"]: entry["loc"] for entry in files}, commits,
            duplication["pairs"]),
    }

    workspace.dir.mkdir(parents=True, exist_ok=True)
    write_json(workspace.run_file, {
        "root": str(root),
        "skill_dir": str(SKILL_DIR),
        "created": datetime.datetime.now().isoformat(timespec="seconds"),
        "settings": asdict(settings),
        "history": history,
        "skipped": skipped,
    })
    write_json(workspace.manifest_file, {"files": files})
    write_json(workspace.graph_file, graph)
    write_json(workspace.clones_file, clone_report)
    write_json(workspace.reach_file, reach_summary)

    files_by_path = {entry["path"]: entry for entry in files}
    # Units are in path order, so each shard holds neighbouring code from the same area.
    shards = pack(units, lambda unit: unit["loc"], settings.shard_loc, settings.shard_files)
    for number, shard in enumerate(shards, 1):
        for lens in tier1_lenses:
            _write_tier1_task(workspace, root, task_id_for("T1", number, lens), lens, shard, files_by_path, graph, importers)

    code_loc = sum(f["loc"] for f in files if not f["is_test"]) or 1
    return {
        "files": len(files),
        "loc": sum(f["loc"] for f in files),
        "modules": len(graph["modules"]),
        "segmented_files": sum(1 for u in units if u.get("segment", {}).get("part") == 1),
        "history": history,
        "duplication": {
            "clone_pairs": duplication["total_pairs"],
            "duplicated_pct": round(100 * sum(f["duplicated_lines"] for f in files if not f["is_test"]) / code_loc, 1),
            "parallel_trees": [f"{t['a']} ~ {t['b']}" for t in clone_report["parallel_trees"][:5]],
        },
        "reach": {
            "launched_loc": reach_summary["totals"]["launched"]["loc"],
            "manual_only_loc": reach_summary["totals"]["manual"]["loc"],
            "tests_only_loc": reach_summary["totals"]["tests"]["loc"],
            "unreached_loc": reach_summary["totals"]["none"]["loc"],
            "launchers": len(reach_summary["launchers"]),
        },
        "shards": len(shards),
        "tier1_tasks": len(shards) * len(tier1_lenses),
        "skipped": skipped,
    }


def _candidate_paths(root):
    """Prefer git's view of the tree (respects .gitignore); fall back to walking the disk."""
    try:
        listed = subprocess.run(
            ["git", "-C", str(root), "ls-files", "-co", "--exclude-standard", "-z"],
            capture_output=True, check=True,
        ).stdout.decode("utf-8", "replace")
        paths = [p for p in listed.split("\0") if p]
    except (OSError, subprocess.CalledProcessError):
        paths = [p.relative_to(root).as_posix() for p in root.rglob("*") if p.is_file()]
    return sorted(
        p for p in paths
        if not IGNORED_DIRS.intersection(Path(p).parts[:-1])
        and not any(fnmatch.fnmatch(Path(p).name, g) for g in IGNORED_GLOBS)
    )


def _is_test(relpath):
    path = Path(relpath)
    name = path.name.lower()
    return (
        bool(TEST_DIR_NAMES.intersection(part.lower() for part in path.parts[:-1]))
        or name.startswith("test_")
        or any(marker in name for marker in ("_test.", ".test.", ".spec.", "_spec."))
    )


def _read_source(path):
    """Return (text, None), (text, "generated") or (None, skip_reason)."""
    try:
        if path.stat().st_size > MAX_FILE_BYTES:
            return None, "too_large"
        raw = path.read_bytes()
    except OSError:
        return None, "unreadable"
    if b"\0" in raw[:8192]:
        return None, "unreadable"
    text = raw.decode("utf-8", "replace")
    if text.lstrip("\ufeff \t\r\n").startswith("<?xml"):
        return None, "not_code"  # an XML file behind a source extension, such as a Qt translation (.ts)
    # A marker counts at the very top or in a comment; code that merely mentions one (a generator,
    # this scanner) is source.
    header = [line.strip().lower() for line in text.splitlines()[:GENERATED_HEADER_LINES]]
    if any((number < 5 or line.startswith(_COMMENT_STARTS)) and any(m in line for m in GENERATED_MARKERS)
           for number, line in enumerate(header)):
        return text, "generated"
    return text, None


def _read_optional(path):
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None


def _review_units(entry, text, chunk_lines):
    """One unit per file, or one per segment when the file is too long for a focused review."""
    lines = text.splitlines()
    bounds = _segment_bounds(lines, chunk_lines)
    if len(bounds) == 1:
        return [{"path": entry["path"], "loc": entry["loc"]}]
    return [
        {
            "path": entry["path"],
            "segment": {"start_line": start, "end_line": end, "part": part, "parts": len(bounds)},
            "loc": sum(1 for line in lines[start - 1:end] if line.strip()),
        }
        for part, (start, end) in enumerate(bounds, 1)
    ]


def _segment_bounds(lines, chunk_lines):
    """Split at top-level definitions (an unindented line after a blank one) near each chunk
    boundary, so a segment rarely cuts a function in half. Returns 1-based inclusive ranges."""
    total = len(lines)
    bounds, start = [], 0
    while total - start > chunk_lines * 1.25:  # never leave a tiny tail segment
        target = start + chunk_lines
        window = range(target, target - chunk_lines // 3, -1)
        cut = next((i for i in window if _is_top_level_start(lines, i)), None)
        cut = cut or next((i for i in window if not lines[i - 1].strip()), target)
        bounds.append((start + 1, cut))
        start = cut
    bounds.append((start + 1, total))
    return bounds


def _is_top_level_start(lines, index):
    line = lines[index]
    return bool(line.strip()) and not line[0].isspace() and not lines[index - 1].strip() and line.strip() not in ("}", "};", "end")


def _write_tier1_task(workspace, root, task_id, lens, shard, files_by_path, graph, importers):
    write_json(workspace.tasks_dir("tier1") / f"{task_id}.json", {
        **task_header("tier1", task_id, root, lens),
        "files": [
            {
                **files_by_path[unit["path"]],
                **({"segment": unit["segment"]} if "segment" in unit else {}),
                "imports": graph["imports"][unit["path"]],
                "imported_by": sorted(importers[unit["path"]]),
            }
            for unit in shard
        ],
    })

def load_manifest(workspace):
    return {entry["path"]: entry for entry in read_json(workspace.manifest_file)["files"]}
